### ISSUE TITLE
Only the first collection by any author appears in search results 

### ISSUE THREAD

**Issue by apjanco** [upenndigitalscholarship/deep#20]

**Comment by ZacharyLesser** [comment]
It looks like only the first collection by any author is appearing

**Comment by ZacharyLesser** [comment]
The checkboxes should filter on the Record Type, which is at the admin level

**Comment by ZacharyLesser** [comment]
The data appears to be all correct, but the search is simply not functioning correctly

**Comment by ZacharyLesser** [comment]
If you look at Titles in admin and search for Comedies, histories, and tragedies (the Shakespeare collection) or The Works (the Jonson collection), you get one result for each item of those titles (instead of one result for each as Titles should work). Interestingly, in each case, the later editions are mislabeled with the date of the first edition. This also lends support to the idea that the problem with later editions of Collections, Latin plays, and some other records not appearing in search results is related to the problem with how Title level is handled in the data model

**Comment by ZacharyLesser** [comment]
This is still not working -- just in case it's not a matter of rebuilding the database. Second edition of COmedies, HIstories, and Tragedies ought to be showing up here. Compare old and new DEEP.  

Before, we were only getting the first result (Whole Contention) so something has improved. But it still is catching only the first edition of each Title per author, I think, when it comes to collections.


[Screen Shot 2023-01-26 at 11.55.04 AM.pdf](https://github.com/upenndigitalscholarship/deep/files/10511643/Screen.Shot.2023-01-26.at.11.55.04.AM.pdf)
[Screen Shot 2023-01-26 at 11.55.54 AM.pdf](https://github.com/upenndigitalscholarship/deep/files/10511644/Screen.Shot.2023-01-26.at.11.55.54.AM.pdf)

**Comment by ZacharyLesser** [comment]
The problem here seems related to a faulty integration of Item -> Edition -> Title perhaps. When you select Record View, the other records do appear (some are variants and should indeed be excluded in Edition View, but others are genuine different Editions that should appear).


https://user-images.githubusercontent.com/40445411/214934864-587591dd-7ff5-4637-b07b-5e37956042c2.mov
