### ISSUE TITLE
Choice fields are not properly updating when you change them

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#31]
If you select Author (Modern Attribution), e.g., then change it to Authorial Status, e.g., the drop-down list of choices does not change. It should change automatically without needing to reload the page

**Comment by apjanco** [comment]
Some progress today, Choice.js alters the select element when initialized. 
1. current approach, reset the div to a select element, but this breaks other things.
2. or if the problem was trying to create a new Choice object, if that is so, then need to 
   a. add a condition to check if it's a vanilla select element or an initialized Choice object
   b. if it's already initialized, then clear choices and set new choices

**Comment by apjanco** [comment]
Gentler approach works, TODO breaks OR blocks, need to fix
