### ISSUE TITLE
Use "not in BritDrama" and "not in Annals" instead of "None" for Genre (BritDrama and Annals) 

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#83]
Remove "None" from the list of filter choices for Genre (BritDrama) 

If no data is present in this field, in the record display, it should read "not in BritDrama" instead of "None"

Same for "Genre (Annals)" -- if no data in field, in record display, it should read "not in Annals"

**Comment by apjanco** [comment]
During build, several fields are updated so that None becomes an empty string or 'n/a'. You'll probably want to add "not in BritDrama" in a similar to this [example] for genre Annals (https://github.com/upenndigitalscholarship/deep/blob/fbef5d80b8c45c09ce77a01fefca04ea4e10c5b3/main/management/commands/search_index.py#L109)

**Comment by ZacharyLesser** [comment]
I created a pull request for changes I made to how the two Company of First Production fields display when they have no data. They should now display "n/a" instead of "None".
